### ISSUE TITLE
Error while starting lab - inconsistency of default branch

### ISSUE THREAD

**Issue by bpelikan** [githubtraining/introduction-to-github-apps#139]
## Bug Report

**Current behavior**
Error message while starting lab:
![image](https://user-images.githubusercontent.com/24376947/101378774-ccba6080-38b3-11eb-8c15-55772e3a9a2b.png)

**Reproduction**
1. Go to lab: https://lab.github.com/githubtraining/getting-started-with-github-apps
2. Start
3. On last step while starting lab (preparing repo) I get error message: 
  > There was an error while updating default branch of bpelikan/getting-started-github-apps!

**Expected behavior**
I can start lab without error.

**Possible solution**
Looking at [repository](https://github.com/leereilly/games) that is used in this lab I can see that there default branch is `master` while in prepared repository on my account I have `main` branch. I think this is root of error.

**Comment by brianamarie** [comment]
Hello @bpelikan! As you can tell, we have recently updated Learning Lab courses to use a default branch of `main` instead of `master`. 

The template repo is based on `leeriley/games`, but we pull directly from https://github.com/githubtraining/games. If you try again in a new browser session, do you get the same error?

**Comment by bpelikan** [comment]
Working fine, thanks! 🙂
